### 提取因子

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_excel('FINALPRICE.xlsx')

In [10]:
df1.set_index('Date',inplace = True)

In [44]:
M1 = (df1-df1.shift(1))/df1.shift(1)
M3 = (df1-df1.shift(3))/df1.shift(3)
M6 = (df1-df1.shift(6))/df1.shift(6)
M12 = (df1-df1.shift(12))/df1.shift(12)
y = M1.shift(-1)

In [22]:
M1.values.reshape(1,-1)

array([[nan, nan, nan, ..., nan, nan, nan]])

In [25]:
a = np.random.randn(12).reshape(3,4)
a

array([[ 0.1981851 , -1.18554053, -0.09332306,  0.59612748],
       [ 2.23752293, -1.80055508, -0.12847619, -0.58000573],
       [ 0.25620415,  1.90802736,  1.46880648, -1.50947961]])

In [26]:
a.reshape(1,-1)

array([[ 0.1981851 , -1.18554053, -0.09332306,  0.59612748,  2.23752293,
        -1.80055508, -0.12847619, -0.58000573,  0.25620415,  1.90802736,
         1.46880648, -1.50947961]])

In [31]:
datelist = df1.index.tolist()

In [33]:
bondlist =df1.columns.tolist() 

In [34]:
s1 = bondlist*len(datelist)

In [36]:
s2 = []
for i in datelist:
    for j in bondlist:
        s2.append(i)
        

In [38]:
df0 = pd.DataFrame()
df0['Date'] = s2
df0['bond'] = s1

In [45]:
df0['M1'] = M1.values.reshape(1,-1)[0]
df0['M3'] = M3.values.reshape(1,-1)[0]
df0['M6'] = M6.values.reshape(1,-1)[0]
df0['M12'] = M12.values.reshape(1,-1)[0]
df0['y'] = y.values.reshape(1,-1)[0]

In [47]:
df0.to_excel('demofactor.xlsx')

In [49]:
pd.to_excel(1)

AttributeError: module 'pandas' has no attribute 'to_excel'

In [ ]:
def quanrter2month(df):